### ISSUE TITLE
QoL - Quest Typos

### ISSUE THREAD

**Issue by BaalSalmon** [MasterEnderman/Divine-Equilibrium#1]
**Hmm**
"I'm"*
![image](https://user-images.githubusercontent.com/42051872/60392688-caa07f80-9acd-11e9-9100-4a6e733fe752.png)

**The Floor**
"I'm"*
![image](https://user-images.githubusercontent.com/42051872/60392694-0dfaee00-9ace-11e9-927c-954dbf8dc1f1.png)

**I Quit**
"too"*
![image](https://user-images.githubusercontent.com/42051872/60392708-4bf81200-9ace-11e9-83a6-5698d08e5632.png)

**RIP**
"I'm"*
![image](https://user-images.githubusercontent.com/42051872/60392712-5c0ff180-9ace-11e9-8ff6-309c238ce129.png)
It doesn't flow too well
![image](https://user-images.githubusercontent.com/42051872/60392717-777afc80-9ace-11e9-8618-b188e581af3f.png)
Perhaps "maybe I can take advantage of my newfound regeneration power"?
Although in the long run it isn't too helpful of a regeneration power, more of a gradual degeneration power  ¯\\(ツ)/¯

**Burned field**
"I'm"*
![image](https://user-images.githubusercontent.com/42051872/60392795-71861b00-9ad0-11e9-96c3-94702c51b6ec.png)

**Cut yourself**
"If"*
![image](https://user-images.githubusercontent.com/42051872/60392806-b3af5c80-9ad0-11e9-8750-ed6cf2a46536.png)
"Use"*
![image](https://user-images.githubusercontent.com/42051872/60392810-c9bd1d00-9ad0-11e9-8f7c-5b05cef37a37.png)

**Dirty Harry**
"Apply"*
![image](https://user-images.githubusercontent.com/42051872/60392814-f1ac8080-9ad0-11e9-97eb-0b208efd7743.png)

**Let it grow**
"menu (---). After"*
"bone"*
![image](https://user-images.githubusercontent.com/42051872/60392834-3801df80-9ad1-11e9-9b33-b13369adb312.png)

**Squeezing and Drying**
"Place"*
![image](https://user-images.githubusercontent.com/42051872/60392892-f291e200-9ad1-11e9-8230-8708123c6915.png)

**Need to breath**
"place"*
![image](https://user-images.githubusercontent.com/42051872/60392902-12c1a100-9ad2-11e9-9e57-3642dc527ee4.png)

**Where did all my Items go?**
"is"*
![image](https://user-images.githubusercontent.com/42051872/60392926-5caa8700-9ad2-11e9-8c56-fc32ab5ffd7c.png)

**Comment by BaalSalmon** [comment]
I remembering seeing you say that you don't like doing the quest descriptions and such, I can always help with that :)

**Comment by MasterEnderman** [comment]
@BaalSalmon sure just download the pack switch the questbook to edit mods and improve on the descriptions. or post them here however you want.

**Comment by MasterEnderman** [comment]
Thanks for pointing out all those typos. they should be fixed now.
