### ISSUE TITLE
Make quests require the amount of ingredients needed in subsequent quests

### ISSUE THREAD

**Issue by Cakeotic** [MasterEnderman/Divine-Equilibrium#10]
This issue struck me especially with the frankincense tree and the turf blocks needed, but in general: If you need 8 of some crafting ingredient in quest 2, make quest 1 require 8 of it; Reason being that no one likes going through a lengthy process of creating a resource only to find out they have to do it again when bulk crafting would've been an option.

**Comment by Cakeotic** [comment]
In practice, this would, for example, mean increasing the amount of turf blocks needed for the quest from 2 to 4, so you'd have enough powder for 2 saplings.

**Comment by MasterEnderman** [comment]
there already should be a "[ i ]" tab in JEI that tells you about this?

**Comment by MasterEnderman** [comment]
I changed some amounts in the upcoming update. if you find another questline where this happens be sure to open another issue.
