### ISSUE TITLE
Make creating planks more obvious

### ISSUE THREAD

**Issue by Cakeotic** [MasterEnderman/Divine-Equilibrium#12]
Adding a text that explains that the knife can be used on logs to get planks would be helpful, as there is no indication of it as far as I know.

**Comment by MasterEnderman** [comment]
there already should be a "[ i ]" tab in JEI that tells you about this?
just look up the recipes of wooden planks?

**Comment by MasterEnderman** [comment]
fixed in 0.2.0-pre2
