### ISSUE TITLE
frankincense leaves have no texture

### ISSUE THREAD

**Issue by hurja** [MasterEnderman/Divine-Equilibrium#16]
bedrock sets in fire with clicking. this shouldnt happen right?
frankincense leaves have no texture, upgraded salad works.

**Comment by MasterEnderman** [comment]
i fixed the bedrock for now until, al finishes the custom mod for it.
i have no idea how to fix the leaves. i can reproduce it and tried 6 different ways to fix them, but none of them worked.

**Comment by MasterEnderman** [comment]
https://github.com/Lemonszz/Corvus/issues/5

**Comment by MasterEnderman** [comment]
fixed in the tweaked version of the mod
