### ISSUE TITLE
overhaul Health system (replace no healthy dying with scaling health)

### ISSUE THREAD

**Issue by hurja** [MasterEnderman/Divine-Equilibrium#18]
what if there was a ritual of the forest that could get you just 1 or 2 hearts back
something cheap like 8 saplings
might be just a bad food item but straight 1-2 hearts would be ideal maybe

it would still always cost 8 gold leaves and a sapling in addition of the materials

**Comment by MasterEnderman** [comment]
fixed in v0.2.0-pre5
