### ISSUE TITLE
crash 0.1.3

### ISSUE THREAD

**Issue by hurja** [MasterEnderman/Divine-Equilibrium#2]
https://pastebin.com/x3TGQ74Q

was trying to by solidified air after wood without closing the book bewteen purchases. or something else equally magical.

**Comment by SilverhuntX** [comment]
[crash-2019-07-01_23.02.34-client.txt](https://github.com/MasterEnderman/Divine-Equilibrium/files/3345693/crash-2019-07-01_23.02.34-client.txt)
Similar issue to above except while doing solidified water

**Comment by SilverhuntX** [comment]
https://pastebin.com/x3TGQ74Q
