### ISSUE TITLE
look into problem

### ISSUE THREAD

**Issue by taint19711** [MasterEnderman/Divine-Equilibrium#30]
there is a problem in my test world where i cant place blocks in certain spots

**Comment by hurja** [comment]
im getting this too https://streamable.com/rzeyb in pre5

**Comment by MasterEnderman** [comment]
https://github.com/Lemonszz/Corvus/issues/6

**Comment by MasterEnderman** [comment]
This should be fixed as I'm now using a modified Version of Corvus.
