### ISSUE TITLE
missing recipes

### ISSUE THREAD

**Issue by hurja** [MasterEnderman/Divine-Equilibrium#33]
all soulus bones into bone torches
primitive spade breaks soulus fossil dirt quite slowly
the elemental research book wants me to buy some stages a second time? https://i.imgur.com/i2gT0lO.png air1 and fire1 on this page and second page has earth1 and wood
stone shovel head needs a pebble which isnt available without bedrock in gaia dim?

suggestion: maybe allow some kind of ladder in gaia dim? nvm ther is vine.

**Comment by MasterEnderman** [comment]
fixed in v0.2.0
