### ISSUE TITLE
Remove the gravel requirement from the gravel quest in the Gaia dimension

### ISSUE THREAD

**Issue by Cakeotic** [MasterEnderman/Divine-Equilibrium#34]
Title, the first real quest in the Gaia dimension requires you to collect 8 gravel to turn into 8 flint. Gravel is normally found around/in water, which turns gravel into flint, causing the problem that the player has 8 flint but no gravel collected.

**Comment by MasterEnderman** [comment]
fixed in Version 0.2.0
