### ISSUE TITLE
inventory crafting gives the wrong item

### ISSUE THREAD

**Issue by Kr0nos04** [MasterEnderman/Divine-Equilibrium#36]
I'm not sure why this is happening, might be if holding shift for to short or something similar. but happened twice to me in 5 hours. first time it consumed the right items but gave a wrong output. Second time it consumed one part of the intended recipe and one part of the recipe of the wrong output.

https://clips.twitch.tv/SassyNimbleCourgetteThunBeast
https://clips.twitch.tv/HungryMoistBisonVoteNay

**Comment by MasterEnderman** [comment]
https://github.com/Tschipp/PrimitiveCrafting/issues/17

**Comment by MasterEnderman** [comment]
Fixed by updating the mod to the newest Version.
