### ISSUE TITLE
[Unfinished] Quest descriptions/lore for review

### ISSUE THREAD

**Issue by Dr-Game** [MasterEnderman/Divine-Equilibrium#38]
[DevEq_Quest_Desc-Lore_0.1a.txt](https://github.com/MasterEnderman/Divine-Equilibrium/files/4142110/DevEq_Quest_Desc-Lore_0.1a.txt)

**Comment by MasterEnderman** [comment]
I've transfered the descriptions in your file into the questbook, while localizing all the quests. Please create pull requests from now on, whenever you've worked on the descriptions. :)
