### ISSUE TITLE
Bucket of Water Deletion Bug

### ISSUE THREAD

**Issue by Dr-Game** [MasterEnderman/Divine-Equilibrium#47]
Right-clicking with a Bucket of Water on a Drying Basin that has 500mB of water in it will destroy the Bucket of Water.

**Comment by MasterEnderman** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/903

**Comment by MasterEnderman** [comment]
was fixed by Integrated Dynamics ages ago.
