### ISSUE TITLE
armor for the basic armor quest is not counted due to the crafted version being unbreakable

### ISSUE THREAD

**Issue by DestructivForce** [MasterEnderman/Divine-Equilibrium#51]
In the Basic Armor quest for the "It's so pretty here" quest line, the armor you can craft from 4 pelt and a shard does not count toward the quest due to the unbreakable nbt tag. Cheating in a set without this tag will trigger the task with no problem.

**Comment by MasterEnderman** [comment]
Which Version of the Modpack do you use?

**Comment by DestructivForce** [comment]
Found in 0.2.8, no longer occurs in 0.2.9. Update that fixed this came out a couple hours after I started playing, and I didn't think to check for an update.
