### ISSUE TITLE
All quest titles and their descriptions are missing

### ISSUE THREAD

**Issue by linux-kernelle** [MasterEnderman/Divine-Equilibrium#52]
The title says it all. All quest titles and their descriptions are missing. It's all just meaningless strings of text, like “diveq.quest001.description.name” or “diveq.quest001.title.name”. Using the latest version (0.2.9), though the same issue occurs on older versions as well.

![Screenshot_20200807_205655](https://user-images.githubusercontent.com/69362688/89676102-ba271f00-d8f3-11ea-89ac-f8f5ebf5c395.png)
![Screenshot_20200807_205826](https://user-images.githubusercontent.com/69362688/89676142-c9a66800-d8f3-11ea-86ca-4c5f5fa4c02a.png)

**Comment by MasterEnderman** [comment]
Looks like an import error to me. Which launcher are you using? Could you retry to import the pack and see if this error occurs all the time?

**Comment by linux-kernelle** [comment]
Thanks for the quick response. I'm using MultiMC (because Twitch App isn't a thing on Linux) and I have tried reinstalling the modpack multiple times, but the error persists. I'm not too familiar with Better Questing, so I don't know how to manually import the file(s) that contain the quests and their descriptions.

**Comment by MasterEnderman** [comment]
Well you should have a en_us.lang file under resources/diveq/lang/ this file contains all the localizations for the questbook.

**Comment by linux-kernelle** [comment]
The en_US.lang file exists. It just never gets imported and I can't do so in the GUI menu of the quest book. It's not visible once I navigate to /resources/diveq/lang/ (in the GUI menu).

**Comment by MasterEnderman** [comment]
You can't import a lang file manually. It should load automatically, once the pack starts (it works like an integrated resource pack). Did you change the language to anything else? (That shouldn't cause a problem, but I'm already out of ideas what could be the cause for your problem.) You could also try to press F3+T to reload all external ressources, but as stated before the pack *should* load the lang file by default.

I hope that this isn't something that only happens to linux users. That would be horrible.

**Comment by linux-kernelle** [comment]
The default language is English (US) and I didn't change it. I tried reloading all resources - no luck. It doesn't seem like my computer's locale has any effect on it.

I wonder if others have encountered this as well.

**Comment by Toksyuryel** [comment]
So I was getting this issue too and came here to see if a solution had been found. None had, but I went and checked out that file and decided to compare it to the same file in another pack where I knew it worked. That file was named en_us.lang instead of en_US.lang, so I tried changing the name and what do you know, it worked! All of the quest text is visible for me now.

The ol' case sensitivity got you again it looks like! Just change the name of the file to en_us.lang and all is well.

**Comment by MasterEnderman** [comment]
Thank you for figuring it out. I'll change it to lowercase for the next update so it shouldn't happen again.

**Comment by MasterEnderman** [comment]
It still is very strange that it works for some people but doesn't for others.

**Comment by linux-kernelle** [comment]
Thank you. After renaming the file everything seems to be working fine.

**Comment by Toksyuryel** [comment]
> It still is very strange that it works for some people but doesn't for others.

Nah it's pretty simple, Windows filenames are not case-sensitive while Linux filenames are. So it worked on Windows because the OS didn't care.
