### ISSUE TITLE
Bones are not dropping from bone block, out of hearts.

### ISSUE THREAD

**Issue by josh2ian** [MasterEnderman/Divine-Equilibrium#53]
Version 0.2.9, I have been able to get bone blocks without issue, but following quest instructions (break bone block with fist) just breaks the block and does not drop any bones. I have repeated this to the point of only having a half heart left, as unable to get bones to progress the pack without dying at this stage. I have tried this with and without holding items. I double checked the video to verify that is what Vallen did in his playthrough and it is.

**Comment by MasterEnderman** [comment]
there shouldn't be anything that stops the bones from dropping. sadly i can't reproduce it in my testworld either. are there any additional information you can give to narrow this issue down?

**Comment by josh2ian** [comment]
Odd. I’ve re-made the world a few times as I wanted to make sure it was able to be reproduced, and I kept running out of maximum health so needed a new start. What other information would you need? I downloaded the pack on twitch launcher earlier today and ran face-first into the issue. The only things I changed at all were my movement keybinds. I thought that maybe the bone drops were glitching and falling out of the cube, so I tried placing it away from the floor and such as well but no changes. After breaking well over 20 bone blocks with no drops I figured I should report.

**Comment by Andr0oS** [comment]
I had the same issue, what I did to fix it was to go to the modpack profile on Twitch (click the modpack picture), go to options (click the gear icon in the top-right corner), and then hit Repair Profile. After that I had no problems even in a pre-existing world.

**Comment by DemonLotusYT** [comment]
I just installed the modpack and had the same problem. I will try Andr0oS fix then comment here if it gets fixed

**Comment by DemonLotusYT** [comment]
Repairing profile works for the bone block

**Comment by MasterEnderman** [comment]
Probably a bad export of the pack. Check if this still occurs in 0.2.10 when it's on curseforge (will hopefully be released soon)
