### ISSUE TITLE
Craft the automatic constructor is impossible in the void dimension

### ISSUE THREAD

**Issue by DestructivForce** [MasterEnderman/Divine-Equilibrium#54]
As crystal quartz for the normal bone gear is unobtainable in the void dimension, crafting the automatic constructor is currently not possible there. If the normal bone gear either had a second recipe that could only be made in the void dimension, or the second recipe for the automatic constructor did not require a normal bone gear, this would not be an issue.
![automaticConstructor](https://user-images.githubusercontent.com/50807043/89720645-062c9f00-d99a-11ea-8cec-fc8eae84067d.jpg)
![boneGear](https://user-images.githubusercontent.com/50807043/89720646-06c53580-d99a-11ea-9d64-339cd4152d6b.jpg)

**Comment by MasterEnderman** [comment]
for now just download this ZenScript file drop it in your scripts folder and restart you pack.

https://cdn.discordapp.com/attachments/593428988215558147/741795135020597358/quartz_fix.zs

**Comment by z-Tau** [comment]
I tried your fix, and see the new recipe for Crystal Quartz using a Pyre.  However, the recipe for the Pyre requires oak and jungle bark, neither of which are available in the void dimension.  Possibly the Wildroot drops from tall grass, but I haven't found any yet.

Also the Pyre itself needs to be crafted in a Fey Crafter, which is even more problematic.  Only the wooden stand is available in that recipe.

**Comment by MasterEnderman** [comment]
You should be able to "buy" a pyre in the elemental research book after finishing the Gaia dimension.

**Comment by z-Tau** [comment]
Ahhh!  Thank you, looking there didn't even occur to me.  I can see now what the suggestion to do further researches was about in the quest text.  Perhaps you could re-word the text or provide a little more of a tip about where to look.

**Comment by MasterEnderman** [comment]
No problem. The quest descriptions aren't final yet. My writer is currently working on chapter two of the questbook. :)

**Comment by MasterEnderman** [comment]
This needs some checkup. Furthermore I need to look at the quest description, if it's already mentioned on how to get a pyre in the void dimension.
