### ISSUE TITLE
Mod not responding.

### ISSUE THREAD

**Issue by DragonWriterCat** [MasterEnderman/Divine-Equilibrium#55]
My computer was bumped and shut off suddenly, when I booted the computer back up and tried to start my game up I keep getting a message saying that a mod is not responding. It says to click the link to file a report however when I do this it says it failed to get the link. 
![image](https://user-images.githubusercontent.com/34019372/89793663-beb62800-daeb-11ea-83bc-0fe9fd500428.png)

**Comment by MasterEnderman** [comment]
just look up the crash-report folder inside your instance folder. there should be a file with the name shown in the picture. that's the actual crash report.

**Comment by DragonWriterCat** [comment]
[crash-2020-08-10_09.19.08-server.txt](https://github.com/MasterEnderman/Divine-Equilibrium/files/5058511/crash-2020-08-10_09.19.08-server.txt)
I've never had to file one of these before so I'm not sure if this is the information you need to see to resolve the issue,

**Comment by MasterEnderman** [comment]
Seems like the mod topography got corrupted. Could you try reinstalling your pack and moving your safe over?

**Comment by MasterEnderman** [comment]
Closing due to missing response.
