### ISSUE TITLE
Elemental Research issues

### ISSUE THREAD

**Issue by Ricviu** [MasterEnderman/Divine-Equilibrium#61]
Sometimes when I log back into my game, my elemental research book is full of the original stuff - Water 1, earth 1, more efficient recipes, etc. - despite me having unlocked them repeatedly. All my elemental 'points' remain on the left, but I've taken to cheating some extra points in to counteract this so I can properly buy them. 

When I die in the jungle and get booted back to the starting platform, my points vanish, and opening the book causes the game to crash. Relogging fixes both issues, letting me see my points and open the book normally (and keeping all the things I've unlocked in place, which is why the opening sentence is only 'sometimes'). Crashing via opening the book also keeps my unlocks, so I'm not sure what the trigger for losing progress is.

**Comment by MasterEnderman** [comment]
That's something I already reported to the author.

https://github.com/al132mc/Elemental-Research/issues/15

**Comment by Ricviu** [comment]
Ah, I didn't know sorry

**Comment by MasterEnderman** [comment]
Elemental Research updated a while ago. I'll release a Version with the new Bugfixes soon.
