### ISSUE TITLE
Bone block ritual not working

### ISSUE THREAD

**Issue by Nullucid** [MasterEnderman/Divine-Equilibrium#63]
The ritual for turning glass to bone blocks isn't working. It gives the glass back instead of a bone block.

**Comment by z-Tau** [comment]
You just have to keep placing the glass until it works - it's apparently a mechanic of the mod since it mentions it happening in the in-game manual.

**Comment by Ricviu** [comment]
The above is correct, the rock core will turn into a bone block when glass/bone has been next to it for long enough, but it will keep popping off like it has been until it's complete.

**Comment by MasterEnderman** [comment]
This isn't a real issue. Just the mechanic how the mod works.
