### ISSUE TITLE
Normal Bone Gear not possible to craft in Insomnia Stage

### ISSUE THREAD

**Issue by Andstar** [MasterEnderman/Divine-Equilibrium#66]
I need to craft the Gear to complete the Automatic Constructor Quest in Insomnia Stage because Crystal Quartz is not obtainable in the Void Dimension (at least not to my knowledge).
I have unlocked all Game Stages that are possible at that point.

**Comment by MasterEnderman** [comment]
Duplicate of: https://github.com/MasterEnderman/Divine-Equilibrium/issues/54
