### ISSUE TITLE
Bone Blocks don't drop bone

### ISSUE THREAD

**Issue by alexignacio1** [MasterEnderman/Divine-Equilibrium#69]
when mining a bone block, nothing drops

**Comment by MasterEnderman** [comment]
That seems weird as it works as intended in all of my test worlds. Which launcher are you using to play the pack?

**Comment by alexignacio1** [comment]
curseforge

**Comment by alexignacio1** [comment]
nevermind, closed and reoppened and it worked, don't know what was going on

**Comment by MasterEnderman** [comment]
Alright. ^^' Curseforge is a bit weird sometimes.
